### PR TITLE
Added talk: Profiling, A dive into your application

### PR DESCRIPTION
**Pull request by dennisdegreef**

### CODE REVIEW

**Comment by jaytaph** [comment]
@dennisdegreef could you also create a speaker page as well? The talk page will link to your speaker page (see https://github.com/phpnl/speaker4hire/blob/gh-pages/_posts/2015-08-01-joshuathijssen.md for an example)

**Comment by dennisdegreef** [comment]
Ah yes, was looking for that, overlooked it.

How do they link? I can guess the suffix is the speaker_slug part, how do the dates relate? What purpose do they serve?

**Comment by jaytaph** [comment]
Dates do not matter (it's a jekyll thing that likes to sort things on dates, which is why dates must be present in the filenames as well :(), we don't use them.

The speaker_slug is created to generate a link to your speaker page, so it assumes that your speakerpage uses the same slug (eg: my speakerpage is `DD-MM-YYYY-joshuathijssen.md`, making `joshuathijssen` the slug..   I'm happy if somebody found a more decent and robust way for this :)

**Comment by jrfnl** [comment]
>  I'm happy if somebody found a more decent and robust way for this

You could use jekyll pages or a custom collection instead. That would both get rid of the dates in the file names.

**Pull request merged**
